### ISSUE TITLE
Does not have Emoji 5.0 in non-native sets

### ISSUE THREAD

**Issue by ai** [missive/emoji-mart#148]
@EtienneLem thanks for adding Emoji 5.0 in 2.3.

But, I can’t find it in any non-`native` `set`. Here is an example of the official demo:

* [native](https://i.imgur.com/1zEsIG8.png)
* [emojione](https://i.imgur.com/qmDLEEa.png)

[EmojiOne sprite](https://unpkg.com/emoji-datasource-emojione@4.0.0/img/emojione/sheets/64.png) has all Emoji 5.0 images.

**Comment by EtienneLem** [comment]
According to https://github.com/iamcal/emoji-data/issues/85, emoji-data uses an older emojione version that doesn’t seem to support Unicode 10. Here’s the data we’re getting:

<img width="451" alt="2017-12-11 at 9 18 am" src="https://user-images.githubusercontent.com/436043/33835499-a88fa1be-de54-11e7-8829-d94778e401ac.png">

The Emoji 5.0 in the sprite you linked seems to be Apple’s version. I think emoji-data is fallbacking to the Apple one instead of just being blank.

**Comment by ai** [comment]
Yeap, strange. EmojiOne website has the note about Emoji 5 support.

Anyway, thanks for the link. I will ask `emoji-data` maintainer next.
