### ISSUE TITLE
Native emoji do not render on Windows 7/8

### ISSUE THREAD

**Issue by raviteja83** [missive/emoji-mart#162]
I tried using google, emojione but no luck. is there any possible reason for this.?

**Comment by EtienneLem** [comment]
A specific emoji or all of them? Is this working on https://missive.github.io/emoji-mart ?

**Comment by Meuk** [comment]
Same issue on  Windows 7 and Windows 8(.1). Firefox seems to deal well with it, however, IE11 and Chrome are not working sadly

I've added screenshots

![screenshot from 2018-12-05 13-14-51](https://user-images.githubusercontent.com/207310/49513015-f0470c80-f88f-11e8-8c6f-1d61fd952f60.png)
![screenshot from 2018-12-05 13-15-20](https://user-images.githubusercontent.com/207310/49513018-f1783980-f88f-11e8-9e8f-113633d920cb.png)
![screenshot from 2018-12-05 13-17-00](https://user-images.githubusercontent.com/207310/49513068-153b7f80-f890-11e8-9319-998d2b86e9a4.png)
![screenshot from 2018-12-05 13-17-24](https://user-images.githubusercontent.com/207310/49513078-208eab00-f890-11e8-85f1-579b0cb89fa5.png)

**Comment by ajesina** [comment]
any news on this?

**Comment by arnaudambro** [comment]
up ! @EtienneLem ?

**Comment by isrmicha** [comment]
up!

**Comment by EtienneLem** [comment]
This might’ve been improved in v5 (see https://missiveapp.com/open/emoji-mart). If not; you might want to consider using a set with images instead of native emojis. Native emojis are very limited on older version of Windows (see https://emojipedia.org/windows-emoji-support) and I’m afraid there isn’t much we can do that.
