### ISSUE TITLE
memoizeSize may be called when picker is not at its final size

### ISSUE THREAD

**Issue by ghost** [missive/emoji-mart#191]
Hello,

We have a picker and we have a problem with scrolling to categories. 

When we click one of the categories, `component.top` in `anchor.js` `function scrollToComponent` always gives us less than what top should be, that's why the scrolling doesn't work correctly too.

when I change `category.js` `componentDidMount` as following `component.top` is correct so the scrolling is correct too. 

`this.memoizeSize();` 
--->
```
var that = this;
setTimeout(function () {
     that.memoizeSize();
},1000);
```

What might cause this problem? How to fix it?

**Comment by bmsedat** [comment]
Seems like there is some kind of race condition happening - since it was a timing issue to begin with.

we added `transitionDuration=0` on `Popover` and we could solve the problem.

**Comment by brianneisler** [comment]
@nolanlawson, @EtienneLem
 
I recently ran into this same issue. I believe this is till a bug. My setup is similar where the Picker component is embedded into a Modal that is not shown until the user triggers some action. The modal is then shown and animated onto the page. This seems like it would be a pretty standard setup for this component but I could be mistaken.

The bug presents itself in a way where the flags category (last category i'm using) is the category that is selected and no other categories are selectable.

The issue seems to be that the size of emoji sheet is measured before it is actually rendered. There is then nothing that triggers a recalculation of the category size since this only happens when a property changes here...

https://github.com/missive/emoji-mart/blob/master/src/components/picker/nimble-picker.js#L226

or when an emoji is selected here...
 
https://github.com/missive/emoji-mart/blob/master/src/components/picker/nimble-picker.js#L299

I worked around this issue by adding a hack that changes the title of the picker by adding a single space to it. This is done after the Modal is made visible but before it is animated. This seems to fix the issue.

**Comment by nolanlawson** [comment]
@brianneisler Hm, it seems that the reason this is happening is:

1. You load the picker at a certain size
2. It calls memoizeSize
3. Then you animate it to another size
4. memoizeSize is not called again

I can see a few potential solutions to this problem:

1. Not doing layout in JavaScript at all, i.e. get rid of memoizeSize somehow
2. Use ResizeObserver (in supported browsers) to detect size changes
3. Expose an API to allow the user to explicitly call memoizeSize

**Comment by nolanlawson** [comment]
Looking through the code, it seems we can get rid of memoize size if we use native sticky positioning and IntersectionObserver.

**Comment by nolanlawson** [comment]
Update: it is really really hard to replicate the existing behavior using only IntersectionObserver. However, I think the sticky positioning polyfill can probably be safely removed at this point. I don't know if this affects the bug though.
