### ISSUE TITLE
Fallback doesn't fire if the emoji name isn't recognised

### ISSUE THREAD

**Issue by andrewhillcode** [missive/emoji-mart#199]
I'm wrapping everything that matches my colon regex like `:crocodile:` and making them Emoji components. 

The fallback only triggers when a recognised emoji name (like `:shrug:`) is not supported in certain sets (like Messenger). Using something like  `:shrugtest:` won't trigger the fallback and the Emoji component will render nothing instead of a string: `:shrugtest:`

**Comment by darklightblue** [comment]
I am actually facing the same issue, Upon checking the source code it seems that this is where the bug is:

https://github.com/missive/emoji-mart/blob/b1c499fc8d7fbcd89f5bd23015df3d10dcc440e3/src/components/emoji/nimble-emoji.js#L89
(there should be a fallback here)
```
  let data = _getData(props)
  if (!data) {
    return null
  }
```
And: 
https://github.com/missive/emoji-mart/blob/b1c499fc8d7fbcd89f5bd23015df3d10dcc440e3/src/utils/index.js#L81

```
   if (data.emojis.hasOwnProperty(emoji)) {
      emojiData = data.emojis[emoji]
    } else {
      return null
    }
```

**Comment by vivaldi-va** [comment]
definitely feel that the `fallback` callback should fire in this case. Perhaps with an additional argument returning the value you added to the `emoji` prop. 

For instance `emoji=":foo:"` should have the callback arguments of `null` and `:foo:`, which would allow rendering a string fallback, for example.

**Comment by EtienneLem** [comment]
Of course! Made it so `fallback` always receive the `emoji` object (if found) and the `props`. It’s up to the developer to use whatever props they want to handle the fallback. Example in README.

**Comment by tuomohopia** [comment]
The fallback still appears not to fire if the `emoji={..}` is an object instead of a string. For example:
```
emoji={{ id, skin: 1 }}
```
