### ISSUE TITLE
Emojione future support

### ISSUE THREAD

**Issue by joelcuevas** [missive/emoji-mart#262]
As emoji-dataset removed its support for emojione (https://github.com/iamcal/emoji-data/commit/a31b052284fd473381048c2aeba456404ec5457a) ... is there a plan to keep emojione in future versions of emoji-mart or it will be removed too?

**Comment by EtienneLem** [comment]
I’ve been postponing emoji-data upgrades because of that, I feel like a good share of people using emoji-mart relies on the EmojiOne set. We’ll figure out a way to keep supporting it.

**Comment by wis** [comment]
@EtienneLem What's the issue for the Emojione folks? even though there's a free licence for the low res. emojis they can't be used in FOSS projects?

**Comment by EtienneLem** [comment]
According to https://github.com/iamcal/emoji-data/pull/142

> Even though we have Free Licenses available for these, unfortunately, it is against our Terms for them to be made available in Open Source projects and doesn’t allow for proper attribution.

Not sure what they expect as “proper attribution”…

**Comment by rugk** [comment]
Actually, https://www.joypixels.com/licenses/free states for the free license:
> Attribution not required.

Maybe this has changed since this been changed/removed?
So maybe one just needs to re-ask under what conditions you could add it again?
(Maybe state in the Readme that the EmojiOne thing e.g. must not be used for buisnesses or so…)

**Comment by rugk** [comment]
[The full text states](https://d1j8pt39hxlh3d.cloudfront.net/contracts/finalized-pdfs/free-5.1.pdf):
> Include it in open source projects or cryptocurrency projects. ​(we support these types of projectshowever they require a custom license agreement—please contact us at ​licensing@joypixels.com​)

So maybe that would allow a way to still include it, given that you can attribute them in the emoji-picker, I guess?
Maybe just show a text if that is shown.

Otherwise you could maybe provide a way to "inject" such custom emoji sets, so if one of the downstream projects that use this lib may get such a custom license (with attribution in their project [sites]) or so, they can still use it in their projects?

Can we maybe re-open this issue to discuss that future possibilities?
