### ISSUE TITLE
Document how to use emoji-mart without React

### ISSUE THREAD

**Issue by rugk** [missive/emoji-mart#305]
I know, this is maybe a stupid question, but I'd better ask it now.

So: Can I somehow use this without React?

E.g. if there would be release bundles that just use "usual JS" (transpiled via babel or so) and allow me to use the whole lib here with "usual" JS calls or so, that would help me a lot. 😄

**Comment by nolanlawson** [comment]
You can use `emoji-mart` with `inferno`, `react-lite`, or `preact`. In particular, [preact version 10](https://github.com/developit/preact/releases/tag/10.0.0-alpha.0) is very small, about ~14kB minified for the `preact/compat` version.

Then you can wrap it in a custom element using something like [remount](https://www.npmjs.com/package/remount), which allows you to use `emoji-mart` within any framework (or no framework at all). In fact, this is what I'm doing in my project [Pinafore](http://github.com/nolanlawson/pinafore/); I'm using `preact` and `remount`. :)

I don't think it's likely that emoji-mart will switch to Vanilla JS, but since you have these options I think it's close enough to vanilla. :)

**Comment by nolanlawson** [comment]
Let me know if that helps; arguably we should add some documentation around this since it's probably not obvious how emoji-mart can be used in a non-React project.

**Comment by nolanlawson** [comment]
Reopened with the docs label

**Comment by rugk** [comment]
Yes, it seems complex. Also one still has to use some react thing as it seems.
But it would be preferable to have a vanilla js bundle at the end. (Possibly with GitHub releases)

**Comment by nolanlawson** [comment]
`emoji-mart` could offer its own bundle as a custom element, yes. But then we'd have to choose a React flavor (React, preact, react-lite, inferno), and then there's also the question of _which_ components to export (nimble-picker, emoji, etc.), as well as whether or not to include a custom elements polyfill.

I think this is too much responsibility for this project, when compatibility layers like `remount` already exist and are well-documented. I would prefer to just document that it's possible to use emoji-mart outside of React, and provide some pointers on how to do so.

**Comment by nolanlawson** [comment]
@rugk Please see https://github.com/missive/emoji-mart/pull/307. I wrote an end-to-end app showing how to do this. Yes we are asking a bit of the developer, but emoji-mart as a vanilla JS custom element can be done. :slightly_smiling_face:

**Comment by rugk** [comment]
Oh, thanks, I'll have a look at it. :smile:

**Comment by rugk** [comment]
Looks interesting. Note that my definition of "vanilla JS" would also include "without nodejs". 😉

**Comment by rugk** [comment]
Thinking about it again https://github.com/nolanlawson/emoji-mart-outside-react still uses React (i.e. Preact), does not it? The shipped JS code still contains all the JS from preact, just now bundled in a way, so you can use it as a custom element?

**Comment by nolanlawson** [comment]
There is no way I can think of to turn `emoji-mart` into a custom element without this technique, yes. Otherwise you would have to rewrite it as a vanilla JS component.

**Comment by nolanlawson** [comment]
fixed in https://github.com/missive/emoji-mart/pull/307

**Comment by rugk** [comment]
Okay, but certainly thanks for your support!
