### ISSUE TITLE
Add new <Emoji/> component or prop that doesn't use <Button/>?

### ISSUE THREAD

**Issue by pederjohnsen** [missive/emoji-mart#309]
I use the `<Emoji/>` component in multiple places where it doesn't need to be clickable, seems odd to render it as a `<Button/>` in those cases.

Might be nice to either add a new component that renders it visually as before, or add a prop to switch between button and non button?

**Comment by pederjohnsen** [comment]
I'd happily make a PR, but would like to know which integration people would prefer.. Separate component or a prop to decide how it renders.

**Comment by EtienneLem** [comment]
A props definitely sound like the best approach. But now that I think about it, the default should be a `<span>`. The Picker could specify that it requires a button, but I feel like the `<Emoji>` component when used to render an emoji outside of the picker would rarely require a button vs. a span.

**Comment by nolanlawson** [comment]
The problem is that `nimble-emoji.js` has its own click listener, which means that semantically it should be a button. Otherwise it should be completely static, and some other parent wrapper should handle the click behavior.

(Keep in mind I changed it to a button to improve accessibility, since as a span it is completely inaccessible to screen readers, unless you explicitly add `role="button"` and custom behavior to handle keyboard events properly, which is a lot more work than just making it a `<button>`. :slightly_smiling_face:)

**Comment by nolanlawson** [comment]
It sounds like we could make `NimbleEmoji` a `<span>`, and then whenever it's used inside of emoji-mart it could be wrapped in a new component, call it `NimbleEmojiButton` or something.

**Comment by nolanlawson** [comment]
Hm, although there is also `emoji.js` which imports `nimble-emoji.js`. If neither do anything with the `onClick` prop, then isn't that a breaking change?

**Comment by nolanlawson** [comment]
Perhaps it would be simpler to just use a prop after all. `clickable={false}` or something like that.

**Comment by hiredgun** [comment]
In my case, the switch to button turned out to be a breaking change since now it triggers form submission whenever an emoji is used and clicked inside a form (default button tag behavior when "type" prop is not provided). This change was introduced in a new minor version so people may not expect anything to break. 

@nolanlawson IMO it was a good choice to switch to button but what about just setting `type="button"` on the button tag? this way:
- it should turn off default behavior on the button which will prevent forms from submission
- it should be still semantically correct in terms of accessibility (and probably make your eslint `jsx-a11y` rules happy)
- it shouldn't require an additional prop
- it should preserve previous behavior thus not breaking any functionality

I guess that the main issue for @pederjohnsen is that after the switch to the button, there is an outline displayed around an emoji after a click event which is a default browsers' behavior due to the accessibility reasons. Anyone can opt-out of this behavior by setting `outline: 0` in CSS on a particular tag or just use some CSS reset to turn it off for an entire project.

**Comment by EtienneLem** [comment]
Decided to go this way:

- `<button>`  with `type=button` (thanks for the tip) only when emoji is clickable (not by default)
- `<span>` otherwise

Handled in #329
