### ISSUE TITLE
(Windows/Linux) Native emoji hover background is off-center

### ISSUE THREAD

**Issue by vesai** [missive/emoji-mart#319]
Chrome 73.0.3683.86
You can see it in this picture:
<img width="375" alt="Снимок экрана 2019-03-23 в 16 36 58" src="https://user-images.githubusercontent.com/5502415/54865672-cb1cd200-4d8a-11e9-8b33-e0344072790e.png">
I think it may have same reason with https://github.com/missive/emoji-mart/issues/310

**Comment by nolanlawson** [comment]
This also repros with the native emoji on Linux. Yes, the hover is off-center.

**Comment by nolanlawson** [comment]
I tried manually setting a left/top offset on the emoji, but I can't seem to find a solution that will work on both Linux and Windows. It seems to be due to the fact that that native emoji overflow their bounding container, and I'm not sure how (or if we even can) measure them. Those emoji fonts are also different on different platforms (Mac, Linux, Windows).

**Comment by nolanlawson** [comment]
Interesting, this bug _only_ repros on Windows and Linux. And on Ubuntu, it looks more off-center in Chrome than in Firefox due to the different emoji fonts used (EmojiOne versus Twemoji). On Windows, it looks roughly the same across Chrome/Firefox/Edge.

This may not be solvable without extremely fragile rules that check for certain combinations of browsers and OS'es.

**Comment by seahorsepip** [comment]
Found a solution for at least correctly centering the icons:

1. Remove width (24px) and height(24px) from icon `<span>`.
2. Also add `position: absolute; top: 50%; left: 50%; transform: translate(-50%, -50%);` to the same `<span>`.
3. Make parent `<span>` (`emoji-mart-emoji emoji-mart-emoji-native`) 36px width & height, add position relative;

The idea behind this is that each icon is 24px (`font-size: 24px;`) inside a wrapper of 24px with 6px padding creating a total of 36px. But on some systems the reality is that `font-size: 24px;` does not result in a 24px emoji and there's no way to force it.

So instead we should embrace the fact that the icon can be larger than 24px inside a 36px container and just center it through `position: absolute; top: 50%; left: 50%; transform: translate(-50%, -50%);` or maybe flexbox centering would work too.

I'll create a PR.

**Comment by Emericano** [comment]
Any update ?

**Comment by JonathanXu1** [comment]
^^

**Comment by torgeadelin** [comment]
Same.

**Comment by svkale** [comment]
Can we just remove width and height of span in button?
<img width="804" alt="BCJ4QLpou8" src="https://user-images.githubusercontent.com/69069085/153032739-ac5236a7-3890-4b6a-91b0-1121531f9377.png">

**Comment by ICSnakes** [comment]
> Can we just remove width and height of span in button? <img alt="BCJ4QLpou8" width="804" src="https://user-images.githubusercontent.com/69069085/153032739-ac5236a7-3890-4b6a-91b0-1121531f9377.png">

That messes up the grid alignment, not all icons on Windows are equal width. Also the grid is designed for 24x24 items, if the items are larger or smaller you'll get different layout on different platforms. The centering fix above uses the elements own size to center it, percentages in transform are based on the element size instead of parent element.

**Comment by seahorsepip** [comment]
> Can we just remove width and height of span in button? <img alt="BCJ4QLpou8" width="804" src="https://user-images.githubusercontent.com/69069085/153032739-ac5236a7-3890-4b6a-91b0-1121531f9377.png">

That messes up the grid alignment, not all icons on Windows are equal width. Also the grid is designed for 24x24 items, if the items are larger or smaller you'll get different layout on different platforms. The centering fix above uses the elements own size to center it, percentages in transform are based on the element size instead of parent element.

**Comment by svkale** [comment]
![image](https://user-images.githubusercontent.com/69069085/153039719-c115f652-bbb6-4cd4-8b2f-8a21420bd75c.png)
Then maybe decrease font size?

**Comment by seahorsepip** [comment]
> ![image](https://user-images.githubusercontent.com/69069085/153039719-c115f652-bbb6-4cd4-8b2f-8a21420bd75c.png) Then maybe decrease font size?

Reducing the font size would require you to target that specific user agent (Windows and Linux) to make sure you don't make the icons too small on e.g. Mac OS, which quickly becomes a mess of OS specific code. Ideally you'd want all OS to give a square 1:1 ratio same size icon but that's not the case. New Windows 11 icons don't seem to have fixed this either, they're still too big. In the end, I gave up on fixing the icon size and fixed the centering only instead.

**Comment by EtienneLem** [comment]
This should be fixed in latest version. Please reopen an issue if that’s not the case.
