### ISSUE TITLE
Search bug

### ISSUE THREAD

**Issue by vesai** [missive/emoji-mart#327]
When you write "fam" in search field you see duplicate key error in console.
<img width="852" alt="Снимок экрана 2019-03-26 в 12 58 52" src="https://user-images.githubusercontent.com/5502415/54980385-67331d00-4fc7-11e9-9ed9-5f3f2faa3fd4.png">

If you continue write "family" you will see more same emoji.

**Comment by curtistimson** [comment]
From what I can tell this is caused by each emoji not having a unique identifier and instead depending on the first "short name" to produce the `id`.

```
id = short_names[0]
```
https://github.com/missive/emoji-mart/blob/master/src/utils/emoji-index/nimble-emoji-index.js#L26

With the example above both of the emojis (Family & Man Woman Boy) are returning `man-woman-boy` as the first "short name".
