### ISSUE TITLE
Render a specific emoji set

### ISSUE THREAD

**Issue by ryan-ds** [missive/emoji-mart#328]
I am currently using the google emoji set like this
```jsx
<NimblePicker
  onSelect={onSelect}
  sheetSize={64}
  set="google"
  data={data}
  title="Select an emoji"
  native={false}
/>
```

Now in the onSelect method, how can we obtain the google specific emoji instead of the native emoji?

**Comment by EtienneLem** [comment]
To render a specific emoji with a set, you can use the `<Emoji />` component with the object received in your `onSelect` callback.

```js
onSelect(emoji) {
  // `emoji` object to be used with Emoji component
}
```
```jsx
<Emoji emoji={emoji} set='google' size={16} />
```

**Comment by ryan-ds** [comment]
@EtienneLem Is it possible to render this in a textarea or input? Like slack does?

**Comment by EtienneLem** [comment]
“Not really” since inputs and textareas can only contains characters and the non-native sets are images. Unless it’s somehow possible to download and force Google’s [Noto Color Emoji](https://www.google.com/get/noto/help/emoji/) font on your input, but I’ve never tried. Not sure it would actually work.

That being said, you could use a rich text editor instead of an input. https://draftjs.org is an RTE for React. Have never worked with Draft.js myself, so I can’t provide an example sorry.
