### ISSUE TITLE
[Feature] Render custom scroll component or scroll component container

### ISSUE THREAD

**Issue by kesha-antonov** [missive/emoji-mart#347]
Hey!

Nice lib

Any plans on this?

**Comment by nolanlawson** [comment]
I'm sorry, can you explain what you're requesting?

**Comment by kesha-antonov** [comment]
Hey!

I use https://github.com/goldenyz/react-perfect-scrollbar
And I want to add styled scrollbars.
I just need to wrap vertical list of emojis with this component. So in emoji-mart we have list with container element ```div```. I want to use custom component

**Comment by nolanlawson** [comment]
It looks like perfect-scrollbar is a JavaScript-based custom scrollbar (i.e. not CSS-only). These kinds of custom scrollbars are typically bad for performance and accessibility (e.g. they [disallow browser scrolling optimizations](https://blogs.windows.com/msedgedev/2017/03/08/scrolling-on-the-web/) and run extra JS on the main thread).

For pure CSS scrollbar modifications, emoji-mart doesn't use shadow DOM and so you can just select the scrollable element inside of it and apply whatever CSS overrides you would like. e.g. `scrollbar-width`: https://developer.mozilla.org/en-US/docs/Web/CSS/scrollbar-width.

I would recommend this approach instead of allowing for fully custom scrollbars. Let me know if that helps!
