### ISSUE TITLE
All.json is always there :'(

### ISSUE THREAD

**Issue by peacepostman** [missive/emoji-mart#376]
Hello,

I know that this issue seems to be fixed now but i am still struggling to remove all.json from our webpack final build.

I am calling the picker via this snippet

```
import NimblePicker from 'emoji-mart/dist-es/components/picker/nimble-picker'
import data from 'emoji-mart/data/emojione.json'
```

And I am calling the emoji renderer via this snippet

```
import NimbleEmoji from 'emoji-mart/dist-es/components/emoji/nimble-emoji'
import data from 'emoji-mart/data/emojione.json'
```

Did any of you have any idea why my final build looks like this

<img width="400" alt="Capture d’écran 2019-10-29 à 13 33 49" src="https://user-images.githubusercontent.com/16117861/67767374-c7ec7180-fa50-11e9-979b-3d123880e865.png">

Best regards,

- react version : 16.8.6
- webpack version : 4.12.0
- emoji-mart version: 2.10.0

**Comment by zypronger** [comment]
Do you solve this problem? I met the same problem.

**Comment by peacepostman** [comment]
Humm, actually yes but its more a trick than a permanent solution :D

In package.json `"postinstall": "node ./build-tools/clear-emoji-file.js"`
Then the target script : 

```
const fs = require('fs')

try {
  var rootDir = process.cwd()
  var file = `${rootDir}/node_modules/emoji-mart/data/all.json`
  fs.writeFileSync(file, '{}', 'utf8')
  console.log('Emoji-mart all.json file is now empty')
} catch (error) {
  console.error(error)
}

```

![work](https://user-images.githubusercontent.com/16117861/69521899-58d73f80-0f60-11ea-84dd-53092f259697.jpg)

**Comment by nolanlawson** [comment]
It's possible to use the nimble picker without including the JSON in the JavaScript file itself. In fact this is probably a good idea, since it's [better for performance to use `JSON.parse()` instead of directly inlining](https://joreteg.com/blog/improving-redux-state-transfer-performance).

[Here is an example of how to do it](https://github.com/nolanlawson/pinafore/blob/7596d905ab860850662354f6d2769f9092ce8a5b/src/routes/_react/createEmojiMartPickerFromData.js#L14).  Basically instead of doing

```js
import data from 'emoji-mart/data/emojione.json'
```

You would do:

```js
const data = await fetch('/some/static/path/emojione.json')
```

Then you would host the JSON file wherever you host your static data files. Or put it in IndexedDB or wherever you like. :)
