### ISSUE TITLE
Emoji picker component breaking in MacOS High Sierra with native icon-sets

### ISSUE THREAD

**Issue by siwalikm** [missive/emoji-mart#467]
**Steps to repro:**
- Open the [demo website](https://missive.github.io/emoji-mart/) in any MacOS device running high sierra or below.
- Observe multiple emojis breaking

I realise this might not be an issue with the picker itself but high-sierra might not be supporting certain emojis (the one's breaking here doesn't appear at all in the native mac emoji picker or on other apps like slack's emoji picker).

**Probable solutions**
- I would expect the picker to not show an emoji in the picker if its enable to parse it
- or have a prop array to pass emoji names we want to not show(aka which are breaking)
_edit: I noticed the `emojisToShowFilter` prop which we might use to pass an exhaustive list as an option_
- anything better you might be able to suggest

**This is how it looks at the moment in MacOS High Sierra:**
![emojimart](https://user-images.githubusercontent.com/20061595/101123428-dffecf00-361a-11eb-8a7c-714b7a1e310f.gif)

**Comment by kozlowskam** [comment]
still an issue! 
reproduced it on Mojave.

**Comment by siwalikm** [comment]
@kozlowskam for my usecase I wanted the picker to be backward compatible till high-sierra so I came up with an exhaustive list of all emojis not supported in high sierra and filtered them out by passing the filter config to the component. So this should work for Mojave too.

Here's that list https://gist.github.com/siwalikm/07339dcc47bf6672243d0df4145e56cc

**Comment by kozlowskam** [comment]
thanks!
would be better if the ones which don't have property 'native' would be filtered out instead of displayed as square tho! 
it already finds them and display them as squares instead of icons with ':native: "true"'

**Comment by EtienneLem** [comment]
@gregsadetsky When using native emojis, I’m afraid there’s no fixing it. See https://emojipedia.org/emoji-13.0, you most likely see broken emojis there as well, right?

The one thing we’re now doing in v5 is to try and find the latest emoji version supported by your browser when using native emojis and ignore versions above that one. The way to test is kind of naive and may require a different approach depending on what your browser is rendering on Catalina. See https://github.com/missive/emoji-mart/blob/main/packages/emoji-mart/src/helpers/native-support.js

[Here’s an HTML file](https://gist.github.com/EtienneLem/66483d23516eddeb00ccc3a23d421fd5) that you can open in your browser, it displays the canvas that the script uses. Can you take a screenshot of what you’re seeing on Catalina? Thanks!

**Comment by gregsadetsky** [comment]
- I do see broken emojis on https://emojipedia.org/emoji-13.0/ , yes.

- I'm afraid that the test isn't working, since it's returning v13.1

safari v13.1.3
<img width="66" alt="safari-v13 1 3" src="https://user-images.githubusercontent.com/1017304/168877538-501ea376-73c0-4a08-b23f-069f8c748862.png">

chrome v101.0.4951.64
<img width="79" alt="chrome-v101 0 4951 64" src="https://user-images.githubusercontent.com/1017304/168877533-f0f83ebd-3727-4fb4-b59f-77e5a40ae349.png">

firefox v100.0
<img width="68" alt="ff-v100 0" src="https://user-images.githubusercontent.com/1017304/168877536-2226e1b5-30f7-40ff-bb7b-1a20bd19c366.png">

- I just tried [is-emoji-supported](https://github.com/koala-interactive/is-emoji-supported), which also does a [similar-ish canvas check](https://github.com/koala-interactive/is-emoji-supported/blob/master/src/is-emoji-supported.ts#L44), although it's a little bit more involved.

I understand that emoji-mart is dependency-free, so I'm not sure what the easiest/best solution would be (integrate the same canvas logic if the license allows it, etc.)

**Comment by EtienneLem** [comment]
Great, thanks for checking. Yeah, I was aware of [is-emoji-supported](https://github.com/koala-interactive/is-emoji-supported). Upon second look at their pretty lightweight codebase (👍🏼), I’d feel very comfortable having it as a dependency. Consider it done for next version.
