### ISSUE TITLE
Question: anyone with 50,000 custom emojis? 

### ISSUE THREAD

**Issue by cabello** [missive/emoji-mart#545]
Hello,

We've been using emoji-mart successfully for 15 months now, such a nice React component.

We are going through uncharted territory now, we allow our customers to add custom Emojis, and we have clients with thousands of them, think 8,000, or 51,000. Context: we import them from Slack that's why they are able to have so many, because they've been using and customizing Slack for years.

I see some prior issues and entries related to this topic:
* https://github.com/missive/emoji-mart/issues/426
* https://github.com/missive/emoji-mart/issues/72
* https://github.com/missive/emoji-mart/issues/6
* https://github.com/missive/emoji-mart/pull/539
* https://github.com/missive/emoji-mart/pull/510

To have an idea of size of the payload ~50,000 results in an API payload of ~5MB.

I don't want every emoji picker user to download 5MB when trying to add a reaction to it.

I was thinking not only we need lazy loading, virtual window, but also a way to let a search hit a backend API that returns a subset of search results, this way the emoji would stay lightweight, showing recents and the standard emoji set.

Anyone would like to join me on this quest?
Would a PR for such support be welcomed?

**Comment by scottwarren** [comment]
@cabello I know it's been quite a while since you posted this, so hopefully this isn't too much of a bother :-). I'm interested in helping out -- do you have something specific in mind? 

In usage of this, I don't have 50,000 emojis, but I can see the benefit of being able to improve the rendering of the emojis. Considering the likely large size of this change, I'd say one would need to break it down into smaller PRs.

**Comment by EtienneLem** [comment]
The latest version uses a virtualized list. Number of emojis shouldn’t impact the performance as much as it used to.
