### ISSUE TITLE
emoji-mart: fix or fork?

### ISSUE THREAD

**Issue by srmagura** [missive/emoji-mart#644]
emoji-mart is a nice component but it has some serious issues:

1. `Picker` configuration is effectively static, i.e. props are ignored. #580, #588, #624
2. `<em-emoji>` does not rerender if its attributes change. #643
3. The developer experience is not great when using React, for both the `Picker` and `<em-emoji>` components. The API is very different from what React developers are used to, and it is hard to use correctly in the context of React. For example, you can easily end up with multiple instances of the Picker in your DOM. Example of this: #617
4. There are no TypeScript type definitions for v5. #576
5. Some additional issues which I have posted PRs for: #641, #642
6. Lacking documentation ("coming soon"), especially for usage in React.

While 4 - 6 are solvable, issues 1 - 3 appear to be core issues with this library which may be much harder to solve.

**IMO the best path forward is to fork the library and rewrite the components to be normal React components.**
- Would anyone be interested in using this fork? 
- Would anyone be interested in helping write it?

The fork would still use `@emoji-mart/data`, since maintaining the database of emojis is the hard part.

@EtienneLem What are your thoughts on this?

**Comment by EtienneLem** [comment]
Thanks for voicing your concerns @srmagura. I just pushed a few fixes related to SSR / NextJS. This should help in making it easier to use with React. On that note, I do think using web component is the way to go instead of maintaining a React-only library. I will look into adding a specific React wrapper, to make it even more seamless.

Main issue with props / config is currently being worked on, there’s been an oversight in the way it was designed for sure.

**Comment by EtienneLem** [comment]
I believe all issues have been addressed.
