### ISSUE TITLE
Error following example with React Native

### ISSUE THREAD

**Issue by joehiggs** [missive/emoji-mart#66]
<img width="367" alt="screen shot 2017-04-21 at 12 58 03 am" src="https://cloud.githubusercontent.com/assets/5335593/25264597/a7400f90-262d-11e7-93e8-bf73855049a1.png">
Importing the Picker and inserting the component as shown in the example results in this error. Is this package compatible with React Native?

**Comment by joehiggs** [comment]
I see now in the source code the use of divs etc

**Comment by pederjohnsen** [comment]
@joehiggs not sure if you're still interested, but I've started work on porting Emoji Mart to React Native:
https://github.com/pederjohnsen/emoji-mart-native

**Comment by pederjohnsen** [comment]
Just an update, the port to React Native have since been transferred to my works github account (my github account now only hosts a fork) it's still in beta (needs some cleaning up and there are some remaining things to be fixed), but we currently use it in production ourselves so it's in a workable state:
https://github.com/thinkproductivity/emoji-mart-native/releases

It has however only been tested on Android for the moment...

**Comment by joehiggs** [comment]
@pederjohnsen Just saw this. Thanks for reaching back out. Actually, @sskhandek, I, and others ended up creating our own keyboard as  part of the app we're working on, Opico. The keyboard was open sourced a couple months ago. Check it out here if you'd like: https://github.com/sskhandek/react-native-emoji-input
