### ISSUE TITLE
Grab-bag of miscellaneous possible improvements

### ISSUE THREAD

**Issue by JustinDrake** [missive/emoji-mart#69]
For [my own project](https://openbazaar.chat/) I have forked emoji-mart (which is totally awesome!) with the following miscellaneous improvements. If there is demand to put any of these improvements into emoji-mart I would be happy to file PRs 👍 .

- [x] [Frequently used default](https://github.com/missive/emoji-mart/pull/64)
- [ ] [Smoother anchor bar transitions](https://github.com/missive/emoji-mart/pull/68)
- [ ] Search bar fixed at the top (similar to Slack)
- [ ] Search bar icon (similar to Slack)
- [ ] Clear search functionality
- [ ] Permanent scrollbar (on Chrome)
- [ ] Click on preview icon to toggle skin tone picker
- [ ] Prettier `.emoji:hover` CSS (similar to Slack)
- [ ] Misc CSS cleanups

**Comment by EtienneLem** [comment]
I really like what you did with the picker! Thanks for submitting the issue 🤘 

---

> Frequently used default

In retrospective: I can see how the defaults choice can be tricky. Would you be in favor of being able to provide the default list instead of using the hardcoded one (the one I re-did)?

> Smoother anchor bar transitions

Will look into the PR soon. I like the not-over-the-top-subtle-way you did it. 👍 

> Search bar fixed at the top

That has been done on my end too, I’ll be pushing and closing that issue shortly.

> Search bar icon

👍 

> Clear search functionality

👍 

> Permanent scrollbar

👍 I do like it. We just need to make sure it looks okay on Windows (if you’re not already on Windows (I’m not, but have access to)).

> Click on preview icon to toggle skin tone picker

I’m neither for nor against. It can however be useful when you want to just close the tone picker without selecting any.

> Prettier `.emoji:hover` CSS

That one we really wanted to be different than Slack. While EmojiMart is very much inspired by theirs, the goal wasn’t to make an exact copy. That being said it does look pretty nice on OB, but I’m pretty sure it wouldn’t fit on Missive. I don’t think I would want to force that style for everyone using the lib, but I would gladly accept a PR making it an option via a props 👍. Would be nice to have a default hardcoded array of HEX colors and allow devs to pass a different array of colors. Someone could only use 2, etc.

> Misc CSS cleanups

👍 All in for cleanups. Vanilla CSS may also start to become a little bit less practical. I wouldn’t mind using SCSS w/ Autoprefixer if need be.

## In other news:
Performance updates coming soon 😛

**Comment by JustinDrake** [comment]
Awesome, sounds good. I was going to mention performance, and I'm very glad you brought it up!

In terms of icons (for the search icon, as well as clear icon) I have been using font-awesome. What is your source for the icons? Would you be open to using font-awesome throughout? What do you suggest?
